### ISSUE TITLE
'mbcs' codec can't decode bytes in position

### ISSUE THREAD

**Issue by AlmiAlmo** [MMMZZZZ/Nextion2Text#11]
Windows 10 x64 (UTF8 experimental support enabled)

Nextion editor V1.62.2
Device: NX4832T035_011
Command:  `python ./nextion2text/Nextion2Text.py -i ./HMI_FILE.hmi -o ./sources`

```
Traceback (most recent call last):
  File "nextion2text\Nextion2Text.py", line 1750, in <module>
    hmi = HMI(hmiFile)
  File "nextion2text\Nextion2Text.py", line 1611, in __init__
    self.header = HMIHeader(self.raw)
  File "nextion2text\Nextion2Text.py", line 1419, in __init__
    self._processData(self.__getHeaderData())
  File "nextion2text\Nextion2Text.py", line 1506, in _processData
    obj = HMIContentHeader(self._raw, index)
  File "nextion2text\Nextion2Text.py", line 1419, in __init__
    self._processData(self.__getHeaderData())
  File "nextion2text\Nextion2Text.py", line 1477, in _processData
    self.name    = data[0].decode("ansi").rstrip("\x00")
  File "G:\LangAndCompilers\Python\Python3\lib\encodings\mbcs.py", line 21, in decode
    return mbcs_decode(input, errors, True)
UnicodeDecodeError: 'mbcs' codec can't decode bytes in position 0--1: No mapping for the Unicode character exists in the target code page.
```

**Comment by AlmiAlmo** [comment]
The problem was in project encoding. (Device - encoding).
When im replace all "ascii" parameters in script to mine encoding "koi8-r" - script was executed as expected.

**Comment by AlmiAlmo** [comment]
Im add pr #12, what has rough workaround. 
Its need to manually change encodingName variables value in head of script to project encoding.
