### ISSUE TITLE
Problems when using file generated by Nextion editor 0.53

### ISSUE THREAD

**Issue by fredrikbergquist** [MMMZZZZ/Nextion2Text#8]
This error occurs

Traceback (most recent call last):
  File "C:\Users\fredrik\OneDrive\Dokument\Nextion2Text-master\Nextion2Text.py", line 1744, in <module>
    hmi = HMI(hmiFile)
  File "C:\Users\fredrik\OneDrive\Dokument\Nextion2Text-master\Nextion2Text.py", line 1605, in __init__
    self.header = HMIHeader(self.raw)
  File "C:\Users\fredrik\OneDrive\Dokument\Nextion2Text-master\Nextion2Text.py", line 1413, in __init__
    self._processData(self.__getHeaderData())
  File "C:\Users\fredrik\OneDrive\Dokument\Nextion2Text-master\Nextion2Text.py", line 1500, in _processData
    obj = HMIContentHeader(self._raw, index)
  File "C:\Users\fredrik\OneDrive\Dokument\Nextion2Text-master\Nextion2Text.py", line 1413, in __init__
    self._processData(self.__getHeaderData())
  File "C:\Users\fredrik\OneDrive\Dokument\Nextion2Text-master\Nextion2Text.py", line 1416, in __getHeaderData
    return struct.unpack(self._headerFormat, self._raw[self._headerStart:self._headerStart+self.headerSize])
struct.error: unpack requires a buffer of 28 bytes

**Comment by MMMZZZZ** [comment]
Hi @fredrikbergquist,

Not planning on adding support for such old file versions anytime soon. 

Regards,
Max
